snakefile: workflow/Snakefile
software-deployment-method: apptainer
latency-wait: 60
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
skip-script-cleanup: True
jobname: "comP_{rule}.{jobid}"
jobs:  200
## DRMAA plugin config
executor: drmaa
drmaa-log-dir: drmaa_logs
drmaa-args: >
  -cwd -j y -pe smp {resources.threads}
## Job Resources
set-resources:
  - bakta:threads=8
  - outgroup_bakta:threads=8
  - skani:threads=24
  - busco:threads=8
  - gtdbtk:threads=24
default-resources:
  - threads=1
